cwsd_homepage:
    path:     /home
    defaults: { _controller: CWSDshowcaseBundle:Showcase:index }

cwsd_devpage:
    path:     /dev
    defaults: { _controller: CWSDshowcaseBundle:Showcase:dev }

cwsd_trafficpage:
    path:     /traffic
    defaults: { _controller: CWSDshowcaseBundle:Showcase:traffic }



